[app]
environment = "dev" # use dev/prod/test

[database]
db_type = "postgres"
connection_string = "postgres://postgres:g5480v@127.0.0.1:5432/audioplayer"


[webserver]
address = "0.0.0.0"
port = 6814
ident = "AudioPlayer" #Server Header Value
log_level = "off" #Dont log requests in Terminal

[log]
file = "latest.api.log"